# Generated by Django 3.1 on 2020-09-19 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0002_main_idea_model_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='second_idea_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Le_gestionnaire_app.main_idea_model')),
            ],
        ),
    ]
