# Generated by Django 3.1 on 2020-09-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0003_second_idea_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='second_idea_model',
            old_name='type',
            new_name='categorie',
        ),
    ]
