# Generated by Django 3.1 on 2020-09-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0008_programme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='programme',
            new_name='programme_model',
        ),
    ]
