# Generated by Django 3.1 on 2020-09-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0009_auto_20200922_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme_model',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Le_gestionnaire_app.second_idea_model'),
        ),
    ]
