# Generated by Django 3.1 on 2020-09-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0010_auto_20200922_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_idea_model',
            name='idea',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='programme_model',
            name='idea',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='second_idea_model',
            name='idea',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='third_idea_model',
            name='idea',
            field=models.CharField(max_length=60),
        ),
    ]
