# Generated by Django 3.1 on 2020-09-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Le_gestionnaire_app', '0012_auto_20200923_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme_model',
            options={'ordering': ['date']},
        ),
    ]
